= TechNexion Yocto 3.0 Zeus 5.4.y GA BSP

This BSP is a TechNexion release providing support NXP i.mx series processors

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir edm_yocto
$: cd edm_yocto
For Yocto Zeus 3.0:
$: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b zeus_5.4.y-next -m imx-5.4.70-2.3.0.xml
$: repo sync -j8

== Create build environment

Set up build environment on host PC:

The build environment is tested under ubuntu 18.04/20.04.

Please ensure there is at least 8~16GB memory or 16GB SWAP space in ubuntu.

Install required packages:
[source,console]
$: sudo apt-get install gawk wget git git-core diffstat unzip texinfo gcc-multilib build-essential \
chrpath socat cpio python python3 python3-pip python3-pexpect \
python3-git python3-jinja2 libegl1-mesa pylint3 rsync bc bison \
xz-utils debianutils iputils-ping libsdl1.2-dev xterm \
language-pack-en coreutils texi2html file docbook-utils \
python-pysqlite2 help2man desktop-file-utils \
libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake \
groff curl lzop asciidoc u-boot-tools libreoffice-writer \
sshpass ssh-askpass zip xz-utils kpartx vim screen

== Prepare WIFI/BT firmware

Add firmware package in Yocto build:
Add argument "WIFI_FIRMWARE=y" in build instruction. Please refer to following explanation.

== Configurations for setup script

`“MACHINE”` is the target of build. It usually corresponds to the name of SOM or SBC.

For more information, please check the file under `“sources/meta-tn-imx-bsp/conf/machine”`.

`DISTRO` is the new way to configure for any backends.

`“-b”` specify the build directory.

`“DISPLAY”` is the disply type. This option only works on i.mx6 (i.mx6 Solo/Dual Lite/Dual/Quad) SOMs and doesn’t work for i.mx6ul, i.mx6sx and i.mx7.

`“BASEBOARD”` is the baseboard type.

`“WIFI_MODULE”` is to choose what kind of WLAN is on board. (qca/brcm/ath-pci)

`“WIFI_FIRMWARE”` is to choose to add WLAN firmware files in target rootfs or not. (y/all)


.Build configurations for supported hardware
|===
|Parameter |Available options|Description

|MACHINE
|axon-imx8mm
|Compatible with TechNexion AXON-IMX8MM (i.MX8M Mini)
|
|axon-imx8mp
|Compatible with TechNexion AXON-E-IMX8MP (i.MX8M Plus)
|
|edm-g-imx8mm
|Compatible with TechNexion EDM-G-IMX8MM (i.MX8M Mini)
|
|edm-g-imx8mn
|Compatible with TechNexion EDM-G-IMX8MN (i.MX8M Nano)
|
|edm-g-imx8mp
|Compatible with TechNexion EDM-G-IMX8MP (i.MX8M Plus)
|
|edm-imx8mq
|Compatible with TechNexion EDM-IMX8M (i.MX8M Quad)
|
|pico-imx8mm
|Compatible with TechNexion PICO-IMX8MM (i.MX8M Mini)
|
|pico-imx8mq
|Compatible with TechNexion PICO-IMX8M (i.MX8M Quad)
|
|flex-imx8mm
|Compatible with TechNexion FLEX-IMX8MM (i.MX8M Mini)
|
|pico-imx7
|Compatible with TechNexion PICO-IMX7 (i.MX7 Dual)
|
|edm-imx6
|Compatible with TechNexion EDM-IMX6 (i.MX6 Solo/Duallite/Quad/QuadPlus)
|
|pico-imx6
|Compatible with TechNexion PICO-IMX6 (i.MX6 Solo/Duallite/Quad)
|
|pico-imx6ul
|Compatible with TechNexion PICO-IMX6UL/PICO-IMX6ULL (i.MX6 UltraLite/ULL)

|DISTRO

(The X11 and Framebuffer distros are only supported for i.MX 6 and i.MX 7. i.MX 8 should use xwayland only.
XWayland is the default distro for all i.MX families)
|fsl-imx-x11
|Only X11 graphics. X11 graphics are not supported on i.MX8.

|
|fsl-imx-wayland
|Wayland weston graphics

|
|fsl-imx-xwayland
|Wayland graphics and X11. X11 applications using EGL are not supported

|
|fsl-imx-fb
|Frame Buffer graphics - no X11 or Wayland. Frame Buffer is not supported on i.MX8.

|BASEBOARD

(It specifies the 'baseboard' variable in uEnv.txt)
|pi, nymph, dwarf, hobbit
|Compatible with TechNexion PICO-IMX6/PICO-IMX7
(i.MX6 Solo/DL/Quad/UL/ULL)(i.MX7 Dual).

|
|gnome, fairy, tc0700, tc1000
|Compatible with TechNexion EDM-IMX6
(i.MX6 Solo/DL/Quad/Quad Plus).

|
|pi
|Compatible with TechNexion PICO-IMX8MQ/PICO-IMX8MM/FLEX-IMX8MM
(i.MX8M Quad)(i.MX8M Mini).

|
|wizard
|Compatible with TechNexion EDM-IMX8MQ/PICO-IMX8MQ/PICO-IMX8MM/FLEX-IMX8MM
(i.MX8M Quad)(i.MX8M Mini).

|
|wandboard
|Compatible with TechNexion EDM-G-IMX8MP/EDM-G-IMX8MM/EDM-G-IMX8MN
(i.MX8M Plus)(i.MX8M Mini)(i.MX8M Nano).

|WIFI_MODULE

(It specifies the 'wifi_module' variable in uEnv.txt)
|'qca', 'brcm', 'ath-pci'
|Choose what kind of WLAN is on board.


|WIFI_FIRMWARE
|'y' or 'all'
|'y' option depends on 'WIFI_MODULE'. If you specify 'WIFI_MODULE' as 'qca'. Then, it only add 'qca' firmware package in yocto build.
'all' option will add both 'qca', 'brcm' and 'ath-pci' firmware package in yocto build.
Please refer to section "Prepare WIFI/BT firmware" to ensure you already put firmware files in the right place.

|DISPLAY

(Parameter "DISPLAY" only works on i.mx6/i.mx8m)
(It specifies the 'displayinfo' variable in uEnv.txt)
|lvds7
|(i.mx6) 7 inch 1024x600 LVDS panel

|
|lvds10
|(i.mx6) 10 inch 1280x800 LVDS panel

|
|lvds15
|(i.mx6) 15 inch 1366x768 LVDS panel

|
|hdmi720p
|(i.mx6) 1280x720 HDMI

|
|hdmi1080p
|(i.mx6) 1920x1080 HDMI

|
|lcd
|(i.mx6) 5 inch/7 inch 800x480 TTL parallel LCD panel

|
|lvds7_hdmi720p
|(i.mx6) Dual display output to both 7 inch LVDS and HDMI

|
|custom
|(i.mx6) Reserved for custom panel

|
|mipi5
|(i.mx8m) MIPI-DSI 5 inch panel(with ILI9881 controller)

|
|hdmi
|(i.mx8m) HDMI monitor (the resolution is decided by EDID)

|-b
|<build dir>
|Assign the name of build directory
|===

.Choosing Yocto target image
|===
|Image name |Target

|core-image-minimal
|A small image that only allows a device to boot

|core-image-base
|A console-only image that fully supports the target device
hardware

|core-image-sato
|An image with Sato, a mobile environment and visual style
for mobile devices. The image supports X11 with a Sato
theme, Pimlico applications. It contains a terminal, an
editor and a file manager

|imx-image-core
|An i.MX image with i.MX test applications to be used for
Wayland backends

|fsl-image-machine-test
|An FSL Community i.MX core image with console
environment - no GUI interface

|imx-image-multimedia
|Builds an i.MX image with a GUI without any Qt content

|tn-image-multimedia-full
|Builds an i.MX image with test tools and a GUI without any Qt content

|fsl-image-qt5-validation-imx
|Builds an opensource Qt 5 image. These images are only
supported for i.MX SoC with hardware graphics. They are
not supported on the i.MX 6UltraLite, i.MX 6UltraLiteLite,
and i.MX 7Dual.

|imx-image-full
|Builds an opensource Qt 5 image with Machine Learning
features. These images are only supported for i.MX SoC
with hardware graphics. They are not supported on the
i.MX 6UltraLite, i.MX 6UltraLiteLite, i.MX 6SLL, and i.MX
7Dual.

|===

== Build Yocto for TechNexion target platform
Please don't add argument 'WIFI_FIRMWARE=y' if you don't put firmware files in "sources/meta-tn-imx-bsp/recipes-kernel/linux-firmware/files" .
It would result in build failure. Please refer to section "Prepare WIFI/BT firmware".

=== For AXON-IMX8MM
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=axon-imx8mm source tn-setup-release.sh -b build-xwayland-axon-imx8mm
$: bitbake fsl-image-qt5-validation-imx

=== For AXON-E-IMX8MP
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=axon-imx8mp source tn-setup-release.sh -b build-xwayland-axon-imx8mp
$: bitbake fsl-image-qt5-validation-imx

=== For EDM-G-IMX8MM
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=edm-g-imx8mm source tn-setup-release.sh -b build-xwayland-edm-g-imx8mm
$: bitbake fsl-image-qt5-validation-imx

=== For EDM-G-IMX8MN
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=edm-g-imx8mn source tn-setup-release.sh -b build-xwayland-edm-g-imx8mn
$: bitbake fsl-image-qt5-validation-imx

=== For EDM-G-IMX8MP
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=edm-g-imx8mp source tn-setup-release.sh -b build-xwayland-edm-g-imx8mp
$: bitbake fsl-image-qt5-validation-imx

=== For EDM-IMX8MQ
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=edm-imx8mq source tn-setup-release.sh -b build-xwayland-edm-imx8mq
$: bitbake fsl-image-qt5-validation-imx

=== For PICO-IMX8MM
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=pico-imx8mm source tn-setup-release.sh -b build-xwayland-pico-imx8mm
$: bitbake fsl-image-qt5-validation-imx

=== For PICO-IMX8MQ
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=pico-imx8mq source tn-setup-release.sh -b build-xwayland-pico-imx8mq
$: bitbake fsl-image-qt5-validation-imx

=== For FLEX-IMX8MM
*Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=flex-imx8mm source tn-setup-release.sh -b build-xwayland-flex-imx8mm
$: bitbake fsl-image-qt5-validation-imx

**DISTRO: DISTRO can be replaced to "fsl-imx-wayland"**

=== For PICO-IMX7
*PI baseboard, QT5 with X11 image for 7 inch/5 inch TTL-LCD panel:*
[source,console]
For PICO-IMX7 with QCA WLAN:
$: WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=pico-imx7 BASEBOARD=pi source tn-setup-release.sh -b build-x11-pico-imx7
$: bitbake fsl-image-qt5-validation-imx

=== For EDM-IMX6
*FAIRY baseboard, QT5 with X11 image for 7 inch LVDS panel:*
[source,console]
For EDM-IMX6 with QCA WLAN:
$: DISPLAY=lvds7 WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=edm-imx6 BASEBOARD=fairy source tn-setup-release.sh -b build-x11-edm-imx6
$: bitbake fsl-image-qt5-validation-imx

*GNOME baseboard, QT5 with X11 image for 7 inch/5 inch TTL-LCD panel:*
[source,console]
For EDM-IMX6 with QCA WLAN:
$: WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=edm-imx6 BASEBOARD=gnome source tn-setup-release.sh -b build-x11-edm-imx6
$: bitbake fsl-image-qt5-validation-imx

*TC-0700/TC0710 baseboard, QT5 with X11 image for 7 inch LVDS panel:*
[source,console]
For EDM-IMX6 with QCA WLAN:
$: DISPLAY=lvds7 WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=edm-imx6 BASEBOARD=tc0700 source tn-setup-release.sh -b build-x11-edm-imx6
$: bitbake fsl-image-qt5-validation-imx

*TC-1000 baseboard, QT5 with X11 image for 10 inch LVDS panel:*
[source,console]
For EDM-IMX6 with QCA WLAN:
$: DISPLAY=lvds10 WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=edm-imx6 BASEBOARD=tc1000 source tn-setup-release.sh -b build-x11-edm-imx6
$: bitbake fsl-image-qt5-validation-imx

=== For PICO-IMX6
*PI baseboard, QT5 with X11 image for HDMI output:*
[source,console]
For PICO-IMX6 with QCA WLAN:
$: WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=pico-imx6 BASEBOARD=pi source tn-setup-release.sh -b build-x11-pico-imx6
$: bitbake fsl-image-qt5-validation-imx

=== For PICO-IMX6UL/PICO-IMX6ULL
*PI baseboard, QT5 with X11 image for 5" and 7" TFT-LCD output:*
[source,console]
For PICO-IMX6UL/ULL with QCA WLAN:
$: WIFI_FIRMWARE=y WIFI_MODULE=qca DISTRO=fsl-imx-x11 MACHINE=pico-imx6ul BASEBOARD=pi source tn-setup-release.sh -b build-x11-pico-imx6ul
$: bitbake fsl-image-qt5-validation-imx

== Chromium Browser
Add Chromium package in `conf/local.conf`:

* For X11 on MX6 with GPU, add Chromium into your image
```
CORE_IMAGE_EXTRA_INSTALL += "chromium-x11 rng-tools"
```
* For XWayland or Wayland, add Chromium into your image
```
CORE_IMAGE_EXTRA_INSTALL += "chromium-ozone-wayland rng-tools"
```

== QTWebkit
There are four Qt 5 browsers available. QtWebEngine browsers can be found in:
```
 /usr/share/qt5/examples/webenginewidgets/StyleSheetbrowser
 /usr/share/qt5/examples/webenginewidgets/Simplebrowser
 /usr/share/qt5/examples/webenginewidgets/Cookiebrowser
 /usr/share/qt5/examples/webengine/quicknanobrowser
```
All three browsers can be run by going to the directory above and running the executable found there. Touchscreen can be
enabled by adding the parameters `-plugin evdevtouch:/dev/input/event0` to the executable.

`./quicknanobrowser -plugin evdevtouch:/dev/input/event0`

QtWebengine will only work on SoC with GPU graphics hardware on i.MX 6, i.MX 7 and i.MX 8.
To include Qtwebengine in the image put the following in local.conf or in the image recipe.
```
IMAGE_INSTALL_append = "packagegroup-qt5-webengine"
```

== Qt 5
Note that Qt has both a commercial and open source license options.  Make the decision about which license
to use before starting work on custom Qt applications.  Once custom Qt applications are started with an open source
Qt license the work can not be used with a commercial Qt license.  Work with a legal representative to understand
the differences between each license.

Note Qt is not supported on i.MX 6UltraLite and i.MX 7Dual. It works on X11 backend only but is not a supported feature.

== NXP eIQ machine learning
The meta-ml layer is the integration of NXP eIQ machine learning, which was formerly released as a separate meta-imx-machinelearning layer and is now integrated into the standard BSP image (imx-image-full). 
Note that many of the features
require Qt 5. In case of using other configuration than imx-image-full, put the following in local.conf:
```
IMAGE_INSTALL_append = "packagegroup-imx-ml"
```

== Systemd
Systemd support is enabled as default but it can be disabled by commenting out the systemd settings in
imx/meta-sdk/conf/distro/include/fsl-imx-preferred-env.inc.

== Image Deployment
When build completes, the generated release image is under “${BUILD-TYPE}/tmp/deploy/images/${MACHINE}”:

To decompress the .bz2:
[source,console]
$: bzip2 -fdk fsl-image-XXX.rootfs.wic.bz2 "fsl-image-XXX.rootfs.wic"

or

Use `bmaptool` to flash fsl-image-XXX.rootfs.wic.bz2 directly.


=== For i.mx6/i.mx6ul/i.mx7:

Please refer to the link below to flash the image into eMMC on the target board:

ftp://ftp.technexion.net/development_resources/development_tools/installer[ftp://ftp.technexion.net/development_resources/development_tools/installer]
```
pico-imx6-imx6ul-imx7_otg-installer_xxx.zip
{platform}_generic-installer_xxx.zip
```
=== For i.MX6UL/i.MX6ULL/i.MX6DL/i.MX6Q/i.MX7D/i.MX8MM/i.MX8MQ/i.MX8MP image deploy by "UUU"

Please refer to the link as below to get more detail informations

https://github.com/TechNexion/u-boot-tn-imx/wiki/Use-mfgtool-%22uuu%22-to-flash-eMMC


=== For pico-imx8mm:

1. UUU way

[source,console]
$: sudo uuu -b emmc_all imx-boot-pico-imx8mm-sd.bin tn-image-docker-os-pico-imx8mm.wic

2. UMS way

Another modular way is use ums command on your currect u-boot inside the eMMC, connect the USB OTG cable to host PC, then ums will auto mounting a storage on host PC, ums command as following in u-boot:
[source,console]
$: ums 0 mmc 1

[source,console]
$: sudo dd if=tn-image-docker-os-pico-imx8mm.wic of=/dev/sdx bs=1M

=== For i.mx8:

Please follow the userguide below to flash the image into eMMC on the target board:

https://github.com/TechNexion/u-boot-edm/wiki[https://github.com/TechNexion/u-boot-edm/wiki]



= For Container OS (based on yocto Zeus 3.0):

Container OS: Debian Buster 10 with SW/HW Acceleration

== Download the BSP Source from virtualization manifest file

[source,console]
$: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b zeus_5.4.y-next -m imx-5.4.70-2.3.0-virtualization.xml
$: repo sync -j8

== Modify Build Environment

Base on the existing build environment in ubuntu 18.04.
Install additional packages:

=== Method 1 - Build environment on host PC:

[source,console]
$: sudo apt install docker.io

=== Method 2 - Download Virtual Machine with pre-installed Ubuntu 20.04 and packages

The virtual machine is validated and able to build Yocto 3.0 virtualization.

=== Method 3 - Using a docker container

Modify the dockerfile to include the following

[source,console]
ARG DOCKER_VERSION="18.09.0"
RUN curl -L https://download.docker.com/linux/static/stable/$(uname -m)/docker-${DOCKER_VERSION}.tgz -o /root/docker.tgz && tar -C /root -xvf /root/docker.tgz && mv /root/docker/docker /usr/local/bin/docker && rm -rf /root/docker*
NOTE: This only gets docker (client) binary, there is no need for dockerd daemon within the docker container

[source,console]
ARG USERNAME="jenkins"
ARG DOCKER_GROUP_ID="145"
RUN groupadd -g ${DOCKER_GROUP_ID} docker && gpasswd -a ${USERNAME} docker
NOTE: Must allow user, e.g. ${USERNAME}, in docker container to access /run/var/docker.sock by adding DOCKER_GROUP_ID from host-PC

Then, build the docker container again.

[source,console]
$: docker build -t tn_ubuntu1604 .
$: docker run -it -u jenkins -v /var/run/docker.sock:/var/run/docker.sock -v ${directory_in_host_machine}:${directory_in_docker} tn_ubuntu1604 /bin/bash
(-v: use to bind volume to the directory in host machine to a directory in docker)
(password: jenkins)
NOTE: /var/run/docker.sock must be passed from host-pc to docker container.
      (docker container uses docker.sock to create a sibling container to
       handle packaging of docker image files)
NOTE: host-pc must also have docker daemon installed, e.g. sudo apt install docker.io


== Configurations for setup script

Currently, the only MACHINE configuration supports virtualization build is pico-imx8mm

Please follow the same procedure as describe in Yocto 3.0 above

=== Additional Settings for local.conf
[source,console]
TN_CONTAINER_IMAGE_TYPE = "tar.gz"
BBMULTICONFIG = "container"
TN_CONTAINER_IMAGE = "tn-container-image-lighttpd"
DOCKER_SHAREDIR = "/home/technexion/zeus"
NOTE: DOCKER_SHAREDIR is the shared folder path common to both the yocto build environment and the sibling docker container used to generate separate partition which stores docker image files.

== Build TechNexion target container image

=== For PICO-IMX8MM only
*Docker OS with Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=pico-imx8mm source tn-setup-release.sh -b build-xwayland-imx8mm
$: bitbake multiconfig:container:tn-container-image-lighttpd
NOTE: this lighttpd docker container image is to be packaged into docker-os, and if not build from yocto automatically, one can manually build it.
$: bitbake tn-image-docker-os

== Test Docker Container
Technexion provides various customized docker containers using Debian base OS from DockerHub. The users can use it after booting docker-os with successful network connection.
The following tests are done with console terminal after successfully booted the Docker-OS image.

* Remote Debian with MESA software acceleration GLMARK2 demo

[source,console]
root@yocto:/# docker run -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=wayland-0 -v $XDG_RUNTIME_DIR/wayland-0:/tmp/wayland-0 --user=$(id -u):$(id -g) -t -i technexion/debian-buster-wayland glmark2-es2-wayland

* Remote Debian with VIVANTE hardware acceleration GLMARK2 demo

[source,console]
root@yocto:/# docker run --privileged=true -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=wayland-0 -v $XDG_RUNTIME_DIR/wayland-0:/tmp/wayland-0 --user=$(id -u):$(id -g) -t -i technexion/debian-buster-wayland-hw glmark2-es2-wayland

* Remote Debian with VIVANTE hardware acceleration Terminal Command-Line

Step 1. Create a container with partition mounting

Create container first, and it will link to bash terminal automatically.
[source,console]
root@yocto:/# docker run  --privileged=true --name debian-test -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=wayland-0 -v $XDG_RUNTIME_DIR/wayland-0:/tmp/wayland-0 -v /home/root:/home/mnt --user=$(id -u):$(id -g) -t -i technexion/debian-buster-wayland-hw bash

If not created first, and the user has already created the container, please issue the command to login the container again.
[source,console]
root@yocto:/# docker start <your container hash id>
root@yocto:/# docker exec -it debian-test bash

Step 2. Install Weston package in Debian container
[source,console]
root@docker:/# apt-get update
root@docker:/# apt-get install weston

Step 3. Run weston-terminal in Debian container, and the user can start remote terminal directly from Yocto host
[source,console]
root@docker:/# weston-terminal
