= TechNexion Yocto 2.5 sumo 4.14.y GA Container OS BSP

This BSP is a TechNexion release providing support PICO-IMX8M-Mini System-on-Module

Host OS: Yocto Sumo 2.5

Container OS: Debian Buster 10 with SW/HW Acceleration

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir edm_yocto
$: cd edm_yocto
$: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b sumo_4.14.y_GA-stable-virtualization -m imx-4.14.98-2.0.1_patch.xml
$: repo sync -j8

== Create build environment
=== Method 1:
Set up build environment on host PC:

Our build environment is under ubuntu 16.04.

Install required packages:
[source,console]
$: sudo apt-get install gawk wget git git-core diffstat unzip texinfo gcc-multilib build-essential \
chrpath socat cpio python python3 python3-pip python3-pexpect \
xz-utils debianutils iputils-ping libsdl1.2-dev xterm \
language-pack-en coreutils texi2html file docbook-utils \
python-pysqlite2 help2man desktop-file-utils \
libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake \	
groff curl lzop asciidoc u-boot-tools libreoffice-writer \
sshpass ssh-askpass zip xz-utils kpartx vim screen

=== Method 2:
Download virtual machine with pre-installed Ubuntu 16.04 and packages.

ftp://ftp.technexion.net/development_resources/development_tools/vm

This virtual machine is validated to build Yocto 2.5.

=== Method 3:
Use the dockerfile to setup the build environment:

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04[Install docker on ubuntu 16.04]

After fetch yocto source code, create a docker image from a dockerfile.
[source,console]
$: cd sources/meta-tn-imx-bsp/tools/container
$: docker build -t tn_ubuntu1604 .
$: docker run -it -u jenkins -v ${directory_in_host_machine}:${directory_in_docker} tn_ubuntu1604 /bin/bash
(-v: use to bind volume to the directory in host machine)
(password: jenkins)

== Prepare WIFI/BT firmware
There are two kinds of WLAN module on TechNexion boards.
One is Broadcom(BRCM) WLAN(includes BCM4330/BCM4339(AP6335)/BCM43438(AP6212)), the other is Qualcomm(QCA) WLAN(includes QCA9377-3/QCA6174).
Because of the license restriction, please contact TechNexion FAE or Sales to get licensed firmware files.

After getting the firmware binary:
.. Decompress the tarball and put all the firmware files into `sources/meta-tn-imx-bsp/recipes-kernel/linux-firmware/files`.

The directory `sources/meta-tn-imx-bsp/recipes-kernel/linux-firmware/files` is the place to put WIFI/BT firmware files.

.. Add firmware package in Yocto build:
Add argument "WIFI_FIRMWARE=y" in build instruction. Please refer to following explanation.

== Configurations for setup script

`“MACHINE”` is the target of build. It usually corresponds to the name of SOM or SBC.

For more information, please check the file under `“sources/meta-tn-imx-bsp/conf/machine”`.

`DISTRO` is the new way to configure for any backends.

`“-b”` specify the build directory.

`“DISPLAY”` is the disply type. This option only works on i.mx6 (i.mx6 Solo/Dual Lite/Dual/Quad) SOMs and doesn’t work for i.mx6ul, i.mx6sx and i.mx7.

`“BASEBOARD”` is the baseboard type.

`“WIFI_MODULE”` is to choose what kind of WLAN is on board. (qca/brcm/ath-pci)

`“WIFI_FIRMWARE”` is to choose to add WLAN firmware files in target rootfs or not. (y/all)


.Build configurations for supported hardware
|===
|Parameter |Available options|Description

|MACHINE
|pico-imx8mm
|Compatible with TechNexion PICO-IMX8MM (i.MX8M Mini)

|DISTRO

(The X11 and Framebuffer distros are only supported for i.MX 6 and i.MX 7. i.MX 8 should use xwayland only.
XWayland is the default distro for all i.MX families)
|fsl-imx-wayland
|Wayland weston graphics

|BASEBOARD

(It specifies the 'baseboard' variable in uEnv.txt)
|pi, nymph, dwarf, hobbit
|Compatible with TechNexion PICO-IMX6/PICO-IMX7
(i.MX6 Solo/DL/Quad/UL/ULL)(i.MX7).

|WIFI_MODULE

(It specifies the 'wifi_module' variable in uEnv.txt)
|'qca', 'brcm', 'ath-pci'
|Choose what kind of WLAN is on board.


|WIFI_FIRMWARE
|'y' or 'all'
|'y' option depends on 'WIFI_MODULE'. If you specify 'WIFI_MODULE' as 'qca'. Then, it only add 'qca' firmware package in yocto build.
'all' option will add both 'qca', 'brcm' and 'ath-pci' firmware package in yocto build.
Please refer to section "Prepare WIFI/BT firmware" to ensure you already put firmware files in the right place.

|DISPLAY

(Parameter "DISPLAY" only works on i.mx6/i.mx8m)
(It specifies the 'displayinfo' variable in uEnv.txt)
|mipi5
|(i.mx8m) MIPI-DSI 5 inch panel(with ILI9881 controller)

|-b
|<build dir>
|Assign the name of build directory
|===

.Choosing Yocto target container image
|===
|Image name |Target

|tn-image-docker-os
|Technexion custom container os image

|===

== Build Yocto for TechNexion target platform
Please don't add argument 'WIFI_FIRMWARE=y' if you don't put firmware files in "sources/meta-tn-imx-bsp/recipes-kernel/linux-firmware/files" .
It would result in build failure. Please refer to section "Prepare WIFI/BT firmware".

=== For PICO-IMX8MM
*Container OS with Xwayland image:*
[source,console]
$: WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=pico-imx8mm source edm-setup-release.sh -b build-xwayland-imx8mm
$: bitbake tn-image-docker-os

*DISTRO: DISTRO can be replaced to "fsl-imx-wayland"*

== Chromium Browser
Add Chromium package in `conf/local.conf`:

* For XWayland or Wayland, add Chromium into your image
```
CORE_IMAGE_EXTRA_INSTALL += "chromium-ozone-wayland rng-tools"
```

== QTWebkit
To start to go to /usr/share/qt5/examples/webkitwidgets/browser and run browser

== Qt
Note that Qt has both a commercial and open source license options.  Make the decision about which license
to use before starting work on custom Qt applications.  Once custom Qt applications are started with an open source
Qt license the work can not be used with a commercial Qt license.  Work with a legal representative to understand
the differences between each license.

== Systemd
Systemd support is enabled as default but it can be disabled by commenting out the systemd settings in
imx/meta-sdk/conf/distro/include/fsl-imx-preferred-env.inc.

== Image Deployment
When build completes, the generated release image is under “${BUILD-TYPE}/tmp/deploy/images/${MACHINE}”:

Image Flashing to the pico-imx8mm:

1. UUU way

[source,console]
$: sudo uuu -b emmc_all imx-boot-pico-imx8mm-sd.bin tn-image-docker-os-pico-imx8mm.wic

2. UMS way

Another modular way is use ums command on your currect u-boot inside the eMMC, connect the USB OTG cable to host PC, then ums will auto mounting a storage on host PC, ums command as following in u-boot:
[source,console]
$: ums 0 mmc 1

[source,console]
$: sudo dd if=tn-image-docker-os-pico-imx8mm.wic of=/dev/sdx bs=1M

== Test Docker Container
Technexion provide different kind of custom docker container using Debian base OS from DockerHub, the users can use it after netowk connection success.

* Remote Debian with MESA software acceleration GLMARK2 demo

[source,console]
root@yocto:/# docker run -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=wayland-0 -v $XDG_RUNTIME_DIR/wayland-0:/tmp/wayland-0 --user=$(id -u):$(id -g) -t -i technexion/debian-buster-wayland glmark2-es2-wayland

* Remote Debian with VIVANTE hardware acceleration GLMARK2 demo

[source,console]
root@yocto:/# docker run --privileged=true  -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=wayland-0 -v $XDG_RUNTIME_DIR/wayland-0:/tmp/wayland-0 --user=$(id -u):$(id -g) -t -i technexion/debian-buster-wayland-hw glmark2-es2-wayland

* Remote Debian with VIVANTE hardware acceleration Terminal Command-Line

Step 1. Create a container with partition mounting

Create container at the first time, it will link to bash terminal automaticially.
[source,console]
root@yocto:/# docker run  --privileged=true --name debian-test -e XDG_RUNTIME_DIR=/tmp -e WAYLAND_DISPLAY=wayland-0 -v $XDG_RUNTIME_DIR/wayland-0:/tmp/wayland-0 -v /home/root:/home/mnt --user=$(id -u):$(id -g) -t -i technexion/debian-buster-wayland-hw bash

If not first time, the user already created the container, please issue the command to login the container again.
[source,console]
root@yocto:/# docker start <your conatiner hash id>
root@yocto:/# docker exec -it debian-test bash

Step 2. Install Weston package in Debian container
[source,console]
root@docker:/# apt-get update
root@docker:/# apt-get install weston

Step 3. Run weston-terminal in Debian container, and the user can start remote terminal directly from Yocto host
[source,console]
root@docker:/# weston-terminal

=== For i.mx8:

Please follow the userguide below to flash the image into eMMC on the target board:

https://github.com/TechNexion/u-boot-edm/wiki[https://github.com/TechNexion/u-boot-edm/wiki]

